version: '1.0'
stages:
  - build
  - test
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: aleksandrcodefresh/ng-CI-CD
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
  unit_test_step:
    stage: test
    commands:
      - yarn test
    when:
      steps:
      - name: BuildingDockerImage
        on:
        - success